version: "3.8"
services:
  database:
    image: postgres:15-alpine
    restart: always
    hostname: $POSTGRES_HOST
    env_file:
      - app.env
    ports:
      - ${PC_POSTGRES_PORT}:${CONT_POSTGRES_PORT}
    volumes:
      - repository:/var/lib/postgresql/repository
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nats-streaming:
    command:
      - "--cluster_id"
      - ${CLUSTER_ID}
    image: library/nats-streaming:latest
    restart: always
    container_name: nats-streaming
    ports:
      - ${PC_NATS_PORT1}:${CONT_NATS_PORT1}
      - ${PC_NATS_PORT2}:${CONT_NATS_PORT2}
    volumes:
      - ./volumes/nats_data_store:/repository:Z

volumes:
  data: