version: "3.8"
services:
  database:
    image: postgres:15-alpine
    restart: always
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/repository
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nats-streaming:
    command:
      - "--cluster_id"
      - ${CLUSTER_ID}
    image: library/nats-streaming:latest
    restart: always
    container_name: nats-streaming
    ports:
      - 4222:${NATS_PORT1}
      - 8222:${NATS_PORT2}
    volumes:
      - ./volumes/nats_data_store:/repository:Z

volumes:
  data: