version: "3.8"
services:
  database:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    hostname: ${POSTGRES_HOST}
    ports:
      - 5432:${POSTGRES_PORT}
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  nats-streaming:
    command:
      - "--cluster_id"
      - ${CLUSTER_ID}
    image: library/nats-streaming:latest
    restart: always
    container_name: nats-streaming
    ports:
      - 4222:${NATS_PORT1}
      - 8222:${NATS_PORT2}
    volumes:
      - ./volumes/nats_data_store:/repository:Z

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
      nats-streaming:
        condition: service_started
    networks:
      - default
    ports:
      - 8080:${APP_PORT}

volumes:
  data: