port: "8080"

db:
  host: "localhost"
  port: "5432"
  username: "postgres"
  dbname: "natsLearnDB"
  sslmode: "disable"

nats:
  serverURL: "nats://localhost:4222"
  clusterID: "test-cluster"
  clientProducer: "producer"
  clientSubscriber: "subscriber"
  subject: "model"

model:
  jsonFilePath: "internal/models/model.json"